### ISSUE TITLE
new LibreOffice version no longer found

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/jpiel-recipes#8]
LibreOffice has changed the versioning schema from "semantic" to "calendar", so the recipe will no longer find the new version.

Could you please update the recipe to reflect this?

Thank you.

**Comment by jpiel** [comment]
This was done already a few hours ago.

**Comment by jpiel** [comment]
you must now use Latest/Previous instead of fresh/still

See issue #7

**Comment by mallej** [comment]
Hi Jayce, thanks for updating the recipe. You could update the Description in the recipe to better explain what strings are possible in the version key.

**Comment by workflowsguy** [comment]
@jpiel 

> This was done already a few hours ago.

thank you!

> you must now use Latest/Previous instead of fresh/still

I was not aware of this parameter. My override seems to have been created automatically using "fresh".

**Comment by jpiel** [comment]
It’s a fresh news. ;)LibreOffice changed there naming convention and so their release page.  Then the manifest had to use the new tags. -- Jayce PielLe 12 févr. 2024 à 18:31, workflowsguy ***@***.***> a écrit :﻿
@jpiel

This was done already a few hours ago.

thank you!

you must now use Latest/Previous instead of fresh/still

I was not aware of this parameter. My override seems to have been created automatically using "fresh".
